// apps/ng-app/src/app/app.component.ts
import { Component } from '@angular/core';
import '@web-comp-app/shared/ui-components';

@Component({
  selector: 'web-comp-app-root',
  template: `
    <h1>Angular App</h1>
    <button (click)="onIncrement()">Increment</button>
    <wc-counter-value [attr.count]="count"></wc-counter-value>
  `,
})
export class AppComponent {
  count = 0;

  onIncrement() {
    ++this.count;
  }
}

// apps/react-app/src/app/app.tsx
import '@web-comp-app/shared/ui-components';

import { useState } from 'react';

export function App() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <h1>React App</h1>
      <button onClick={() => setCount(count - 1)}>Decrement</button>
      <wc-counter-value count={count}></wc-counter-value>
    </div>
  );
}

export default App;
